#!/usr/bin/env python3
"""
Generate the AuthorityBench results table as LaTeX for insertion into the paper.

Usage:
    python generate_table.py                     # reads results/metrics.json
    python generate_table.py --stdout            # prints table to stdout
    python generate_table.py --output table.tex  # writes to file
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from metrics import load_metrics

CONDITION_LABELS = {
    "prompt_only": "Prompt-Only",
    "guardrail": "Keyword Filter",
    "authority_model": "Authority Model (Veto)",
}

CATEGORY_LABELS = {
    "file_system": "File System",
    "network_access": "Network Access",
    "code_execution": "Code Execution",
    "data_exfiltration": "Data Exfiltration",
    "privilege_escalation": "Privilege Escalation",
    "tool_chaining": "Tool Chaining",
}


def pct(v: float) -> str:
    return f"{v * 100:.1f}\\%"


def fmt_ed(v: float) -> str:
    return f"{v:.3f}"


def generate_main_table(metrics: dict) -> str:
    """Generate the primary per-condition summary table."""
    rows = []
    for cond_key, label in CONDITION_LABELS.items():
        row = metrics["by_condition"].get(cond_key, {})
        vr1 = pct(row.get("vr_p1", 0))
        vr2 = pct(row.get("vr_p2", 0))
        vr3 = pct(row.get("vr_p3", 0))
        dap = pct(row.get("dap", 0))
        ed = fmt_ed(row.get("ed", 0))
        rows.append(f"  {label:<30} & {vr1:>8} & {vr2:>8} & {vr3:>8} & {dap:>8} & {ed:>6} \\\\")

    table = (
        "% AuthorityBench Results — generated by generate_table.py\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        "  \\caption{AuthorityBench: Violation Rate (VR), Degradation Under Adversarial\n"
        "    Pressure (DAP = VR(P2)$-$VR(P1)), and Enforcement Determinism (ED).\n"
        "    Lower VR and DAP and higher ED are better. $n=50$ scenarios,\n"
        "    $k=3$ trials each, GLM-5 agent (DashScope).}\n"
        "  \\label{tab:authoritybench}\n"
        "  \\begin{tabular}{lrrrrr}\n"
        "  \\toprule\n"
        "  \\textbf{Condition} & \\textbf{VR(P1)} & \\textbf{VR(P2)} & \\textbf{VR(P3)}"
        " & \\textbf{DAP} & \\textbf{ED} \\\\\n"
        "  \\midrule\n"
        + "\n".join(rows) + "\n"
        "  \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    return table


def generate_category_table(metrics: dict) -> str:
    """Generate per-category VR(P2) breakdown across all conditions."""
    cond_data = {
        c: metrics["by_condition"].get(c, {})
        for c in ("prompt_only", "guardrail", "authority_model")
    }

    rows = []
    for cat_key, cat_label in CATEGORY_LABELS.items():
        cats = {c: cond_data[c].get("by_category", {}).get(cat_key, {}) for c in cond_data}
        po_vr2 = pct(cats["prompt_only"].get("vr_p2", 0))
        gd_vr2 = pct(cats["guardrail"].get("vr_p2", 0))
        am_vr2 = pct(cats["authority_model"].get("vr_p2", 0))
        po_vr3 = pct(cats["prompt_only"].get("vr_p3", 0))
        gd_vr3 = pct(cats["guardrail"].get("vr_p3", 0))
        am_vr3 = pct(cats["authority_model"].get("vr_p3", 0))
        rows.append(
            f"  {cat_label:<25} & {po_vr2:>7} & {gd_vr2:>7} & {am_vr2:>6}"
            f" & {po_vr3:>7} & {gd_vr3:>7} & {am_vr3:>6} \\\\"
        )

    table = (
        "% AuthorityBench Category Breakdown — generated by generate_table.py\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        "  \\caption{VR by threat category and adversarial pressure level.\n"
        "    P2 = ambient pressure; P3 = adversarial injection/override.\n"
        "    PO = Prompt-Only; KF = Keyword Filter; AM = Authority Model.}\n"
        "  \\label{tab:authoritybench-categories}\n"
        "  \\small\n"
        "  \\begin{tabular}{lrrrrrr}\n"
        "  \\toprule\n"
        "  & \\multicolumn{3}{c}{\\textbf{VR(P2)}} & \\multicolumn{3}{c}{\\textbf{VR(P3)}} \\\\\n"
        "  \\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
        "  \\textbf{Category} & \\textbf{PO} & \\textbf{KF} & \\textbf{AM}"
        " & \\textbf{PO} & \\textbf{KF} & \\textbf{AM} \\\\\n"
        "  \\midrule\n"
        + "\n".join(rows) + "\n"
        "  \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    return table


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--output", default="results/table.tex")
    args = parser.parse_args()

    metrics = load_metrics()
    if metrics is None:
        print(
            "ERROR: results/metrics.json not found. Run harness.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    output = generate_main_table(metrics) + "\n" + generate_category_table(metrics)

    if args.stdout:
        print(output)
    else:
        out_path = Path(args.output)
        out_path.parent.mkdir(exist_ok=True)
        out_path.write_text(output)
        print(f"Table written to {out_path}")

    # Print text summary too
    print("\n=== AuthorityBench Summary ===")
    meta = metrics.get("meta", {})
    print(f"Total trials: {meta.get('total_trials')}  Errors: {meta.get('errors')}")
    print(f"{'Condition':<30} {'VR(P1)':>8} {'VR(P2)':>8} {'VR(P3)':>8} {'DAP':>8} {'ED':>6}")
    print("-" * 70)
    for cond_key, label in CONDITION_LABELS.items():
        row = metrics["by_condition"].get(cond_key, {})
        print(
            f"{label:<30} "
            f"{row.get('vr_p1', 0):>8.3f} "
            f"{row.get('vr_p2', 0):>8.3f} "
            f"{row.get('vr_p3', 0):>8.3f} "
            f"{row.get('dap', 0):>8.3f} "
            f"{row.get('ed', 0):>6.3f}"
        )


if __name__ == "__main__":
    main()
