#!/usr/bin/env python3
"""
Generate AuthorityBench results tables as LaTeX for insertion into the paper.

Usage:
    python generate_table.py                     # reads results/metrics.json
    python generate_table.py --stdout            # prints to stdout
    python generate_table.py --output table.tex  # writes to file
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from metrics import load_metrics

CONDITION_LABELS = {
    "prompt_only": "Prompt-Only",
    "guardrail": "Keyword Filter",
    "authority_model": "Authority Model",
    "authority_model_stateless": "Authority Model ($-H$)",
    "llm_judge": "LLM-as-Judge",
}

CATEGORY_LABELS = {
    "file_system": "File System",
    "network_access": "Network Access",
    "code_execution": "Code Execution",
    "data_exfiltration": "Data Exfiltration",
    "privilege_escalation": "Privilege Escalation",
    "tool_chaining": "Tool Chaining",
}

MODEL_LABELS = {
    "glm-5": "GLM-5",
    "kimi-k2.5": "Kimi-K2.5",
    "minimax-m2.5": "MiniMax-M2.5",
    "gpt-5.4": "GPT-5.4",
}


def pct(v: float) -> str:
    return f"{v * 100:.1f}\\%"


def fmt_ed(v: float) -> str:
    return f"{v:.3f}"


# ── Table 1: Aggregate summary ───────────────────────────────────────────────

def generate_aggregate_table(metrics: dict) -> str:
    agg = metrics.get("aggregate", {}).get("by_condition", {})
    meta = metrics.get("meta", {})
    models = meta.get("models", [])
    total = meta.get("total_trials", 0)
    model_str = ", ".join(MODEL_LABELS.get(m, m) for m in models)

    rows = []
    for cond_key, label in CONDITION_LABELS.items():
        row = agg.get(cond_key, {})
        if not row:
            continue
        ci = row.get("vr_p2_ci", [])
        ci_str = ""
        if ci and len(ci) == 2:
            ci_str = f" [{ci[0]*100:.0f}--{ci[1]*100:.0f}]"
        vr1 = pct(row.get("vr_p1", 0))
        vr2 = pct(row.get("vr_p2", 0))
        vr3 = pct(row.get("vr_p3", 0))
        dap = pct(row.get("dap", 0))
        ed = fmt_ed(row.get("ed", 0))
        rows.append(
            f"  {label:<30} & {vr1:>8} & {vr2:>8}{ci_str} & {vr3:>8} & {dap:>8} & {ed:>6} \\\\"
        )

    table = (
        "% AuthorityBench Aggregate Results — generated by generate_table.py\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        f"  \\caption{{AuthorityBench: aggregate across {model_str}.\n"
        f"    $N={total}$ trials. VR = violation rate, DAP = VR(P2)$-$VR(P1),\n"
        "    ED = enforcement determinism. Lower VR/DAP and higher ED are better.\n"
        "    95\\% Wilson CIs shown for VR(P2).}\n"
        "  \\label{tab:authoritybench}\n"
        "  \\begin{tabular}{lrrrrr}\n"
        "  \\toprule\n"
        "  \\textbf{Condition} & \\textbf{VR(P1)} & \\textbf{VR(P2)} & \\textbf{VR(P3)}"
        " & \\textbf{DAP} & \\textbf{ED} \\\\\n"
        "  \\midrule\n"
        + "\n".join(rows) + "\n"
        "  \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    return table


# ── Table 2: Per-model VR(P2) breakdown ──────────────────────────────────────

def generate_per_model_table(metrics: dict) -> str:
    by_model = metrics.get("by_model", {})
    models = metrics.get("meta", {}).get("models", [])

    n_models = len(models)
    model_headers_vr = " & ".join(
        f"\\textbf{{{MODEL_LABELS.get(m, m)}}}" for m in models
    )
    model_headers_ed = " & ".join(
        f"\\textbf{{{MODEL_LABELS.get(m, m)}}}" for m in models
    )

    rows = []
    for cond_key, label in CONDITION_LABELS.items():
        vr_cells = []
        ed_cells = []
        for m in models:
            cond_data = by_model.get(m, {}).get("by_condition", {}).get(cond_key, {})
            vr_cells.append(pct(cond_data.get("vr_p2", 0)))
            ed_cells.append(fmt_ed(cond_data.get("ed", 0)))
        row = f"  {label:<30}"
        for v in vr_cells:
            row += f" & {v:>8}"
        for e in ed_cells:
            row += f" & {e:>6}"
        row += " \\\\"
        rows.append(row)

    col_spec = "l" + "r" * n_models + "r" * n_models
    cmidrule_vr = f"\\cmidrule(lr){{2-{1+n_models}}}"
    cmidrule_ed = f"\\cmidrule(lr){{{2+n_models}-{1+2*n_models}}}"

    table = (
        "% AuthorityBench Per-Model Breakdown — generated by generate_table.py\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        "  \\caption{Per-model VR(P2) and ED. Cross-model stability confirms\n"
        "    findings are architecture-dependent, not model-dependent.}\n"
        "  \\label{tab:authoritybench-models}\n"
        "  \\small\n"
        f"  \\begin{{tabular}}{{{col_spec}}}\n"
        "  \\toprule\n"
        f"  & \\multicolumn{{{n_models}}}{{c}}{{\\textbf{{VR(P2)}}}} & \\multicolumn{{{n_models}}}{{c}}{{\\textbf{{ED}}}} \\\\\n"
        f"  {cmidrule_vr}{cmidrule_ed}\n"
        f"  \\textbf{{Condition}} & {model_headers_vr} & {model_headers_ed} \\\\\n"
        "  \\midrule\n"
        + "\n".join(rows) + "\n"
        "  \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    return table


# ── Table 3: Per-category breakdown ──────────────────────────────────────────

def generate_category_table(metrics: dict) -> str:
    agg = metrics.get("aggregate", {}).get("by_condition", {})
    conditions = ["prompt_only", "guardrail", "authority_model", "authority_model_stateless", "llm_judge"]
    cond_short = ["PO", "KF", "AM", "AM$-H$", "Judge"]

    rows = []
    for cat_key, cat_label in CATEGORY_LABELS.items():
        cells = []
        for c in conditions:
            cat_data = agg.get(c, {}).get("by_category", {}).get(cat_key, {})
            cells.append(pct(cat_data.get("vr_p2", 0)))
        row = f"  {cat_label:<25}"
        for cell in cells:
            row += f" & {cell:>7}"
        row += " \\\\"
        rows.append(row)

    header_cols = " & ".join(f"\\textbf{{{s}}}" for s in cond_short)

    table = (
        "% AuthorityBench Category Breakdown — generated by generate_table.py\n"
        "\\begin{table}[htbp]\n"
        "  \\centering\n"
        "  \\caption{VR(P2) by threat category and enforcement condition (aggregate across models).\n"
        "    AM$-H$ = authority model without history tracking (stateless ablation).}\n"
        "  \\label{tab:authoritybench-categories}\n"
        "  \\small\n"
        f"  \\begin{{tabular}}{{l{'r' * len(conditions)}}}\n"
        "  \\toprule\n"
        f"  \\textbf{{Category}} & {header_cols} \\\\\n"
        "  \\midrule\n"
        + "\n".join(rows) + "\n"
        "  \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    return table


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--output", default="results/table.tex")
    args = parser.parse_args()

    metrics = load_metrics()
    if metrics is None:
        print(
            "ERROR: results/metrics.json not found. Run harness.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    output = "\n\n".join([
        generate_aggregate_table(metrics),
        generate_per_model_table(metrics),
        generate_category_table(metrics),
    ])

    if args.stdout:
        print(output)
    else:
        out_path = Path(args.output)
        out_path.parent.mkdir(exist_ok=True)
        out_path.write_text(output)
        print(f"Tables written to {out_path}")

    # Text summary
    print("\n=== AuthorityBench Summary ===")
    meta = metrics.get("meta", {})
    print(f"Models: {meta.get('models')}  Total trials: {meta.get('total_trials')}  Errors: {meta.get('errors')}")
    agg = metrics.get("aggregate", {}).get("by_condition", {})
    print(f"{'Condition':<30} {'VR(P1)':>8} {'VR(P2)':>8} {'VR(P3)':>8} {'DAP':>8} {'ED':>6}")
    print("-" * 80)
    for cond_key, label in CONDITION_LABELS.items():
        row = agg.get(cond_key, {})
        if not row:
            continue
        print(
            f"{label:<30} "
            f"{row.get('vr_p1', 0):>8.3f} "
            f"{row.get('vr_p2', 0):>8.3f} "
            f"{row.get('vr_p3', 0):>8.3f} "
            f"{row.get('dap', 0):>8.3f} "
            f"{row.get('ed', 0):>6.3f}"
        )


if __name__ == "__main__":
    main()
